### ISSUE TITLE
[MOVIE]: Captain Marvel (2019)

### ISSUE THREAD

**Issue by paugau** [LizardByte/ThemerrDB#976] opened 2023-02-16 16:50 UTC
### TheMovieDB URL

https://www.themoviedb.org/movie/299537-captain-marvel

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=PdIIrxJyezE

**Comment by ReenigneArcher** [comment] 2023-04-20 18:11
Duplicate of #752

**Closed by ReenigneArcher** 2023-04-20 18:11 UTC
Labels: request-movie
