### ISSUE TITLE
[MOVIE]: 8 Mile (2002)

### ISSUE THREAD

**Issue by samcro1967** [LizardByte/ThemerrDB#812] opened 2023-02-07 00:37 UTC
### TheMovieDB URL

https://www.themoviedb.org/movie/65-8-mile?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=zlJ0Aj9y67c&t=43s

**Comment by ReenigneArcher** [comment] 2023-02-07 02:02
Duplicate of #28

**Closed by ReenigneArcher** 2023-02-07 02:02 UTC
Labels: request-movie
