### ISSUE TITLE
[MOVIE]: Evil Dead Rise (2023)

### ISSUE THREAD

**Issue by carbonbaseunit** [LizardByte/ThemerrDB#1084] opened 2023-07-14 04:29 UTC
### TheMovieDB URL

https://www.themoviedb.org/movie/713704-evil-dead-rise

### YouTube Theme Song Video URL

https://youtu.be/7JevQlNt2NM

**Comment by ReenigneArcher** [comment] 2023-07-14 12:34
Duplicate of #1077

**Closed by ReenigneArcher** 2023-07-14 12:34 UTC
Labels: request-movie
