### ISSUE TITLE
[MOVIE]: Howl's Moving Castle (2004)

### ISSUE THREAD

**Issue by jjnether** [LizardByte/ThemerrDB#912] opened 2023-02-10 18:41 UTC
### TheMovieDB URL

https://www.themoviedb.org/movie/4935?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=f7SS57LFPco

**Comment by ReenigneArcher** [comment] 2023-02-10 18:59
Duplicate of #788

**Closed by ReenigneArcher** 2023-02-10 18:59 UTC
Labels: request-movie
