### ISSUE TITLE
[MOVIE]: Turning Red (2022)

### ISSUE THREAD

**Issue by tylerbickel** [LizardByte/ThemerrDB#349] opened 2023-01-26 01:43 UTC
### TheMovieDB URL

https://www.themoviedb.org/movie/508947

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=cGBIc7dGa94

**Comment by ReenigneArcher** [comment] 2023-02-01 03:30
Duplicate of #180

**Closed by ReenigneArcher** 2023-02-01 03:30 UTC
Labels: request-movie
