### ISSUE TITLE
[MOVIE]: A Star Is Born (2018)

### ISSUE THREAD

**Issue by samcro1967** [LizardByte/ThemerrDB#814] opened 2023-02-07 00:43 UTC
### TheMovieDB URL

https://www.themoviedb.org/movie/332562-a-star-is-born?language=en-US

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=bo_efYhYU2A

**Comment by ReenigneArcher** [comment] 2023-02-07 02:09
Duplicate of #510

**Closed by ReenigneArcher** 2023-02-07 02:09 UTC
Labels: request-movie
