### ISSUE TITLE
[MOVIE]: Dungeons & Dragons: Honor Among Thieves (2023)

### ISSUE THREAD

**Issue by SiriosDev** [LizardByte/ThemerrDB#1133] opened 2023-08-21 15:39 UTC
### Database URL

https://www.themoviedb.org/movie/493529

### YouTube Theme Song Video URL

https://www.youtube.com/watch?v=f2k1JjnY0dQ

**Comment by SiriosDev** [comment] 2023-08-21 18:34
the before one was, strangely, region locked and this is unlocked only in USA, probably a problem of license

**Comment by ReenigneArcher** [comment] 2023-08-21 18:51
This video is the same as what's already in the database.

Duplicate of #1036

**Closed** 2023-08-21 18:51 UTC
Labels: request-theme

**Comment by SiriosDev** [comment] 2023-08-21 19:21
sorry, On the lizardbyte.dev/ThemerrDB site I checked and no sound was starting
